### ISSUE TITLE
Fehler beim verschieben des Backup Archivs

### ISSUE THREAD

**Issue by mschlenstedt** [Woersty/LoxBerry-Plugin-miniserverbackup#1]
Bekomme nach dem Backup (manuell gestartet) folgenden Fehler:

ERR#2005: Gebe auf! Kann Datensicherungs-Archiv nicht in den Downloadbereich verschieben. (Backup_192.168.3.210_20160818055240_19216803210.zip)

Backup Archiv ist aber im Download Bereich vorhanden.

**Comment by Woersty** [comment]
Schau ich mir später an.

**Comment by fhien** [comment]
Habe das Gleiche Problem!
Hatte Versucht Das MS Backup auf Täglich zustellen, dachte er macht automatisch eine Sicherung! Leider sehe ich nur die Dateien bei manuellen Backups.

Fehlermeldung steht auch im Log File

**Comment by Woersty** [comment]
Da fehlte ein Buchstabe..... Ist ab 0.8 gelöst.
