### ISSUE TITLE
Hinweis zu vorzunehmender Konfiguration auf Admin-Interface nicht mehr aktuell

### ISSUE THREAD

**Issue by gahujipo** [Woersty/LoxBerry-Plugin-miniserverbackup#16]
Der folgende Hinweis erscheint auf der Hauptseite des Plugins: 

> Achtung! Im Miniserver Admin-Interface muss die Option FTP, TELNET UND KONFIGURATIONSSOFTWARE auf "Online" gesetzt werden! Anderenfalls ist ein Backup möglicherweise nicht möglich.

Dieses Admin Interface (also http://loxone/admin) scheint in der aktuellsten Version nicht mehr vorhanden zu sein. Die /admin-Seite öffnet sich mit folgendem Inhalt: 

> All admin settings can now be easily adjusted directly from within Loxone Config. For this open the current version of Loxone Config and navigate to "Miniserver / Configure Device".

Der Hinweis sollte somit aktualisiert werden. Habe die Stelle im Quelltext nur nicht gefunden um eine Pull-Request zu schicken.

**Comment by Woersty** [comment]
Das steht in den language.dat Dateien im templates Ordner.
Ich passe es an.
