### ISSUE TITLE
Download-Webinterface hat keine Icons

### ISSUE THREAD

**Issue by Woersty** [Woersty/LoxBerry-Plugin-miniserverbackup#19]
https://github.com/Woersty/LoxBerry-Plugin-miniserverbackup/issues/10#issuecomment-333305661

**Comment by christianTF** [comment]
Kann ich bestätigen (Icons fehlen), noch keine Idee wieso (elfinder hab ich wie man im Repo sieht, gar nicht angegriffen).
Ich suche mal...

**Comment by christianTF** [comment]
Fixed with https://github.com/Woersty/LoxBerry-Plugin-miniserverbackup/pull/21/commits/dfdb93ea7c70f061eafd38e671926d62affecfaa
