### ISSUE TITLE
v09

### ISSUE THREAD

**Issue by fhien** [Woersty/LoxBerry-Plugin-miniserverbackup#2]
Das neu Plugin läst sich nicht installieren
anbei das Log:
<INFO> Starte Plugin-Installation
<OK> Plugin-Archiv erfolgreich hochgeladen
<INFO> Extrahiere Plugin-Archiv
<INFO> Command: /usr/bin/unzip -d /tmp/uploads/YajImesjo6 /tmp/uploads/YajImesjo6/YajImesjo6.zip
Archive:  /tmp/uploads/YajImesjo6/YajImesjo6.zip
31b06b0f877a4c544b7a1997b9b341e9d7dac388
   creating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/LICENSE  
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/README.md  
   creating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/config/
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/config/miniserverbackup.cfg  
   creating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/icons/
 extracting: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/icons/icon_128.png  
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/icons/icon_256.png  
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/icons/icon_512.png  
 extracting: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/icons/icon_64.png  
   creating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/log/
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/log/backuplog.log  
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/plugin.cfg  
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/postinstall.sh  
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/postupgrade.sh  
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/preinstall.sh  
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/preupgrade.sh  
   creating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/templates/
   creating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/templates/de/
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/templates/de/help.html  
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/templates/de/language.dat  
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/templates/de/settings.html  
   creating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/templates/en/
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/templates/en/help.html  
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/templates/en/language.dat  
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/templates/en/settings.html  
   creating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/webfrontend/
   creating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/webfrontend/cgi/
   creating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/webfrontend/cgi/bin/
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/webfrontend/cgi/bin/createmsbackup.pl  
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/webfrontend/cgi/index.cgi  
   creating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/webfrontend/html/
 extracting: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/webfrontend/html/backupstate.txt  
   creating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/webfrontend/html/files/
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/webfrontend/html/files/.htaccess  
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/webfrontend/html/logfile.php  
  inflating: /tmp/uploads/YajImesjo6/LoxBerry-Plugin-miniserverbackup-master/webfrontend/html/style.css  
<OK> Plugin-Archiv erfolgreich entpackt
<FAIL> Das Plugin-Archiv scheint nicht das korrekte Format zu haben. Bitte kontaktiere den Plugin-Entwickler oder versuche es erneut.

Wie funktioniert eigentlich das Täglich backup?

kann bisher nur manuell Sichern

**Comment by Woersty** [comment]
Das ist nicht abwärtskompatibel. Muss Micha erst ein Update vom Loxberry 0.2 rausbringen.

**Comment by Woersty** [comment]
Als Workaround kannst du in der ZIP das Verzeichnis LoxBerry-Plugin-miniserverbackup-master löschen und die Unterordner ins Hauptverzeichnis vom ZIP verschieben

**Comment by fhien** [comment]
Habe ich gerade versucht! geht leider auch nicht!

**Comment by Woersty** [comment]
Hast du nochmal einen Versuch mit der aktuellen Stable-Version vom LoxBerry gemacht?
http://www.loxwiki.eu/display/LOXBERRY/LoxBerry+Links bzw. http://download.loxberry.de/stable/images/
Gruß

**Comment by Woersty** [comment]
Nicht nachstellbar. Bitte mit v0.12 probieren, wenn verfügbar.
