### ISSUE TITLE
Abgestürtzes Backup erkennen 

### ISSUE THREAD

**Issue by Woersty** [Woersty/LoxBerry-Plugin-miniserverbackup#20]
Status für laufendes Backup nach Timeout zurücksetzen.

**Comment by christianTF** [comment]
Ich hab das im LoxBerry Backup mit pgrep gemacht:
https://github.com/christianTF/LoxBerry-Plugin-LoxberryBackup/blob/master/webfrontend/cgi/grep_raspibackup.cgi

Im Javascript rufe ich das cgi ab und prüfe damit, ob es noch PIDs gibt.
https://github.com/christianTF/LoxBerry-Plugin-LoxberryBackup/blob/6e4dec14c63770c8baa75b95922c14c2e103bf9d/templates/multi/backup.html#L123
