### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by zmata** [Woersty/LoxBerry-Plugin-miniserverbackup#26]
Hi, can you add Czech translation from https://github.com/zmata/LoxBerryCz/blob/master/plugins/miniserverbackup/language_cs.ini
Thanks

**Comment by Woersty** [comment]
Hello, unfortunately - for you - I have done a complete redesign.
Can you check again
I have published the current version here: https://github.com/Woersty/LoxBerry-Plugin-miniserverbackup/commit/f40d53931da51ed76e70164d5b98b870a9c28f94
And it's included in PreRelease version 2019.4.4 => https://github.com/Woersty/LoxBerry-Plugin-miniserverbackup/releases/tag/v2019.4.4
You can - if you want - adapt it with http://your_loxberry/admin/system/translate.cgi?form=plugin again

**Comment by Woersty** [comment]
See issue 33 for news.
