### ISSUE TITLE
Backup schlägt fehlt

### ISSUE THREAD

**Issue by andylox** [Woersty/LoxBerry-Plugin-miniserverbackup#27]
Hi, hab in meinem Loxberry 1.2.5.5 eben das aktuelle Plugin installiert und wollte direkt mal ein manuelles Backup machen. das steht dann im log:
ERROR: 2018-12-21 10:33:03 Miniserver #1: ERR#2006: Fehler beim Speichern von: /log Versuch 1 von 5 (Errorcode: 34304)
 ERROR: 2018-12-21 11:06:23 Miniserver #1: ERR#2006: Fehler beim Speichern von: /log Versuch 2 von 5 (Errorcode: 34304)
 ERROR: 2018-12-21 11:39:43 Miniserver #1: ERR#2006: Fehler beim Speichern von: /log Versuch 3 von 5 (Errorcode: 34304)
 ERROR: 2018-12-21 12:13:03 Miniserver #1: ERR#2006: Fehler beim Speichern von: /log Versuch 4 von 5 (Errorcode: 34304)
 ERROR: 2018-12-21 12:46:23 Miniserver #1: ERR#2006: Fehler beim Speichern von: /log Versuch 5 von 5 (Errorcode: 34304)
 ERROR: 2018-12-21 12:46:23 Miniserver #1: ERR#2007: Gebe auf! Wiederholter Fehler beim Speichern von: /log (Errorcode: 34304)
 ERROR: 2018-12-21 12:46:23 : Nicht alle Datensicherungen fehlerfrei erstellt - siehe Logdatei [ENDE]

**Comment by Woersty** [comment]
Schau ich mir an.

**Comment by andylox** [comment]
kann es immer noch am Passwort liegen zum MS?

**Comment by christianTF** [comment]
MSBackup unterstützt nach wie vor keine Umlaute und Sonderzeichen im Passwort.

**Comment by andylox** [comment]
Hab das Passowrt geändert und es hat funktioniert! Danke
