### ISSUE TITLE
v2019.4.6: Zeitpunkt Backups passt nicht bei bestimmten Einstellungen

### ISSUE THREAD

**Issue by gbrehmer** [Woersty/LoxBerry-Plugin-miniserverbackup#40]
Bei Backup Interval 1 Day und Backups to keep 60, wird mehrfach die Stunde ein Backup erstellt. Ich ging davon aus, dass es 1x am Tag gemacht wird und dann bis zu 60 Backups = Tage vorgehalten werden

**Comment by Woersty** [comment]
Habe ich gemerkt. Hast du 2019.4.7 probiert?

**Comment by gbrehmer** [comment]
ah nicht gesehen dass es schon etwas neues gibt, der Raspi 1 ist da bei allem etwas langsam. Melde mich

**Comment by Woersty** [comment]
Ich glaube geht trotzdem nicht. Ich schau nachher mal, was ich übersehen habe.

**Comment by Woersty** [comment]
Ich hoffe, dass es mit v2019.4.7.1 geht.
Ich habe nur mal schnell drüber geguckt.
Hab ich versaubeutelt gehabt, Sorry.
Autoupdate sollte gehen.
