### ISSUE TITLE
Infomail Betreffzeile

### ISSUE THREAD

**Issue by Cobru** [Woersty/LoxBerry-Plugin-miniserverbackup#42]
Kann in der Betreffzeile noch der Name des Miniserver

**Comment by Woersty** [comment]
Ist schon als Bug offen.
Muss ich wie bei Cam Connect komplett selbst machen.
Über die momentan verwendete Loxberry Mailfunktion geht es nicht.

Grüße

**Comment by Woersty** [comment]
Duplikat von #31

**Comment by Woersty** [comment]
Es kommt jetzt nur noch eine Zusammenfassungs-eMail für alle Miniserver.
