### ISSUE TITLE
Feature-Request: Ziel-Verzeichnis

### ISSUE THREAD

**Issue by scharrin2** [Woersty/LoxBerry-Plugin-miniserverbackup#52]
Ich hätte folgenden Feature-Request:

Ich habe bereits am Loxberry ein Filesystem /backup per NFS gemundet.

Gibt es die Möglichkeit, als Backup-Ziel das Verzeichnis /backup/Loxone-MS anzugeben? In der jetzigen Version kann ich ja nur einige Verzeichnisse auswählen.

Viele Grüße,
Christian

**Comment by Woersty** [comment]
Ich denk drüber nach. 💭

**Comment by Woersty** [comment]
Duplikat #69 geschlossen
