### ISSUE TITLE
Netzwerk-Share als Ziel für das Backup

### ISSUE THREAD

**Issue by Shogun1978** [Woersty/LoxBerry-Plugin-miniserverbackup#6]
Einen Vorschlag wollte ich noch zu deinem Tool machen: kannst du eventuell den automatischen Transfer der Backups auf ein anderes Medium (z.B. Netzwerkshare) einbauen? Von der Idee her: der Benutzer gibt einen CIFS oder NFS Share in einer Eingabe-Maske an. Dann wird nach dem Backup mit deinem einfach cp Befehl das Zip auf den Share kopiert. Die Eingabemaske stelle ich mir da noch am kompliziertesten vor. Ich kann das zwar auch intern über einen Cron-Job und ein Automount des Shares für mich selbst lösen, aber für die Community wäre es vielleicht in der GUI etwas angenehmer.

**Comment by Woersty** [comment]
Gefällt mir. Ich überlege mir was.

**Comment by christianTF** [comment]
Ich habe mich ein bisschen umgesehen, was Perl und PHP zu bieten hat.

Zugriff auf Netzwerklaufwerke als Plugin-Funktion finde ich nicht gut. Es beginnt schon mit den Anforderungen CIFS und NFS, die aus Sicht des Entwicklers (z.B. aus Perl oder PHP) völlig anders implementiert werden müssen. 
Außerdem macht es keinen Sinn, dass jedes Plugin "das Rad neu erfindet".

Die wahre und sinnvolle Möglichkeit ist nur via mount oder einfacher/sicherer per autofs. Das könnte als Plugin oder Systemfunktion angeboten werden. 

Alle Plugins brauchen dann nur einen konfigurierbaren Pfad. 

In meiner Anpassung für inkrementelles Update habe ich alle Pfadangaben auf Variablen aus der Plugin-Configdatei umgestellt. Im Webinterface ist es derzeit nicht, aber technisch funktioniert's.

**Comment by derhoeppi** [comment]
Christian gibt es in der 0.18 Version bereits die Möglichkeit das Verzeichnis in dem das Backup landet zu verändern? Ich mache zwar derzeit wöchentlich ein Backup des Raspi, aber ich würde gerne direkt an das MiniserverBackup gelangen ohne das ich ältere RaspiBackups öffnen muss.
Ansonsten wäre die Konfiguration via Webinterface sicherlich nett. Mir würde jedoch auch ein Parameter in der Config ausreichen.

**Comment by Woersty** [comment]
Ich bin leider momentan zu 100% ausgelastet. Im Winter schaffe ich hoffentlich wieder mehr am LoxBerry Projekt zu arbeiten. Vergessen ist das aber alles nicht. Nur verschoben...

**Comment by christianTF** [comment]
@derhoeppi Wenn du meinen Branch genommen hast, findest du die Pfade in /opt/loxberry/config/plugins/miniserverbackup im cfg-File.

**Comment by Woersty** [comment]
Eingebaut ab v2019.4.4
