### ISSUE TITLE
Logfenster zeigt nix an

### ISSUE THREAD

**Issue by mschlenstedt** [Woersty/LoxBerry-Plugin-miniserverbackup#67]
Bleibt leer, obwohl Backup läuft. Manuell gestartet.

V2019.04.20

**Comment by Woersty** [comment]
Liegt am logrotate, muss ich mir was überlegen.
Der löscht die Datei während sie benutzt wird.

**Comment by mschlenstedt** [comment]
Er räumt nur .log Files auf. Wenn du die Endung anders wählst bleiben die Files erhalten. Musst dann nur selber aufräumen. 

Hat jetzt damit nichts zu tun, aber: Warum machst du das in dem Fenster inline und machst nicht einfach einen Link auf den Standard Logmanager. Ist viel übersichtlicher finde ich.

**Comment by mschlenstedt** [comment]
Und Life gucken kannste damit auch. Das gleiche mit dem Filemanager: warum keinen Link auf den Loxberry Filemanager?

**Comment by Woersty** [comment]
Weil mir der externe Logviewer nicht gefällt und ich die Aktivität zusätzlich zum Button sehen will - im gleichen Fenster . Und der Filemanager für mich zum Plugin gehört. Ich ändere mal auf .txt - aufräumen mache ich eh schon selbst im Plugin.
