### ISSUE TITLE
Backup-Verzeichnis nicht frei wählbar

### ISSUE THREAD

**Issue by mschlenstedt** [Woersty/LoxBerry-Plugin-miniserverbackup#69]
das Backup-Verzeichnis ist nicht frei wählbar - das ist blöd. Ich will nicht nach SHARE/Miniserver-Name sichern, sondern nach //Share/Backups/MEINNAME

Warum nicht die LoxBerry-Standards nehmen?!

![image](https://user-images.githubusercontent.com/16830799/56708844-92bc3b00-671e-11e9-8ae1-2d78a2672c9d.png)

**Comment by Woersty** [comment]
Gelöst ab 2019.4.27 coming soon.
