### ISSUE TITLE
Inkrementelles Backup

### ISSUE THREAD

**Issue by christianTF** [Woersty/LoxBerry-Plugin-miniserverbackup#8]
Bei mir dauert das Backup meines Haupt-Miniservers ca. 16 Minuten (gesamt ca. 354 MB).

Ich habe testweise ein Backup mit
wget -a wget.log -m ftp://user:pass@192.168.0.77
durchgeführt (-m ... mirror).
Nach einem Tag dauert das zweite Backup 30 Sekunden.

Ich habe die Dateien stichprobenartig geprüft und Loxone scheint den Timestamp sauber zu aktualisieren.

Man müsste die Dateien des letzten Backups dafür aufheben. Ins Backup-ZIP können dann wieder alle Dateien hinein (wie gehabt).
Ein bisschen Umstellerei im createmsbackup.pl wäre dafür notwendig:
Das $bkpdir müsste erstmal "statisch" nur die MS-Adresse enthalten.
Der Name des ZIPs samt Timestamp könnte dort in eine Variable, und wird dann beim Aufruf von $zipbin verwendet.
Das Cleanup müsste bei Full-Backup vorher passieren, oder bei Inc garnicht. 

Im GUI könnte man für das manuelle Backup einen Switch machen (full, incremental). 
Für das scheduled backup könnte man evt. einen Zeitpunkt nach Tagen setzen, nachdem zuvor das Backup-Verzeichnis geleert wird.

Zumindest von den Statistiken weiß ich, dass die Loxone Firmware beim Reboot die Statistikdateien auf der SD löscht, die im XML nicht mehr referenziert sind.

**Comment by christianTF** [comment]
@Woersty Ich hätte einen Test-Branch mit Änderungen im createmsbackup.pl.
Willst du dir das ansehen?

**Comment by Woersty** [comment]
Sehr gute Idee, schick mal. Bau ich ein.

**Comment by christianTF** [comment]
Ich habe das noch nirgends ausprobiert, und ich habe noch nie Perl programmiert, deswegen entschuldige ich mich gleich im Voraus für alle Fehler :-)

[createmsbackup.pl.txt](https://github.com/Woersty/LoxBerry-Plugin-miniserverbackup/files/465122/createmsbackup.pl.txt)

Ich referenziere in den language.dat auch noch auf eine neue Beschreibung (TXT1031=Inkrementelles Backup). 
Dass nach x Backups alles gelöscht werden soll, ist auch noch nicht drin.

Ich hoffe, das ist verwertbar.

**Comment by christianTF** [comment]
Zur eigenen Referenz:
http://lftp.tech/lftp-man.html
http://sina.salek.ws/content/how-mirrorsync-remote-ftp-folder-local-folder

**Comment by christianTF** [comment]
https://github.com/christianTF/LoxBerry-Plugin-miniserverbackup/commit/5106bec78ec4dc30ed414a98e0a586c9b45d9eb8

Ein paar Optimierungen/Tests muss ich noch machen, aber im Großen und Ganzen funktioniert es schon.

**Comment by Woersty** [comment]
Habe es mal gepullt und installiert. Manuell läuft.
Ich lasse es mal heute Nacht laufen. 
Bin gespannt.

Danke schon mal.

Gruß

**Comment by christianTF** [comment]
Paar Kleinigkeiten und das mit den Verzeichnissen hätt ich noch zu machen:
- Default Compression Level auf 5 (statt 1)  https://github.com/Woersty/LoxBerry-Plugin-miniserverbackup/blob/ed8a9ec3b4e115ab95b90f4e165cb59d51cb1e38/webfrontend/cgi/bin/createmsbackup.pl#L125 - musste ich runtersetzen zum Testen am Pi1
- en/language.dat ist noch nicht up-to-date
- Logfiles (quiet/verbose/debug) ist bei lftp und 7zip noch nicht ganz sauber (alles eher debug, da müsste ich die ganzen Optionen noch durchprobieren)
- Das mit den Verzeichnissen hab ich noch nicht fertig (das aktuelle ungezippte Backup liegt schon in data/currentbackup, aber das workdir ist noch hardcoded in /tmp/miniserverbackup)

Das mit der Compression müsste für einen Public Test jedenfalls hochgestellt werden, weil beim späteren inkrementellen Backup wird der Faktor bei den bestehenden Files im ZIP nicht mehr geändert.

Wiki-Eintrag DRAFT (siehe ganz unten): http://www.loxwiki.eu/pages/editpage.action?useDraft=true&spaceKey=LOXBERRY&draftId=13307469&pageId=9339532
(Wenn du Änderungen machst und nur "schließen", wird es noch nicht gepublished)

**Comment by christianTF** [comment]
Incremental backup in v0.20
