### ISSUE TITLE
CRITICAL: Minimal required LoxBerry version is greater than current LoxBerry version

### ISSUE THREAD

**Issue by KrisDeCaluwe** [Woersty/LoxBerry-Plugin-miniserverbackup#81]
[N28Ii31JZj.log](https://github.com/Woersty/LoxBerry-Plugin-miniserverbackup/files/3186584/N28Ii31JZj.log)

Hi All,

I tried to install the latest version on my loxberry but it faild. All version 2019.5 fail whereas the 2019.4.12.5 installs without any issue. Failure message is:
16.05.2019 12:15:53 CRITICAL: Minimal required LoxBerry version is greater than current LoxBerry version. Cannot install.

Thanks
Kris

**Comment by Woersty** [comment]
The plugin uses a new feature from v2019.5 which was introduced in LoxBerry 1.4.1.1
You have to Upgrade your Loxberry base System to PreRelease.

**Comment by KrisDeCaluwe** [comment]
Thank you it works!

Kind regards,

Kris
