### ISSUE TITLE
Fehler #35 und Plugin kann nicht deinstalliert werden

### ISSUE THREAD

**Issue by AndreasSausner** [Woersty/LoxBerry-Plugin-miniserverbackup#84]
Hallo Christian, 

zuerst einmal vielen dank  für das klasse plugin.

Seit dem 26.9 werden keine log files mehr geschrieben aber dafür stündlich backup's durchgeführt. Der versuch das plugin zu deinstallieren geht nicht Eine  deinstallation wird zwar "durchgeführt" und mit OK bestätigt ist aber bei den Plugins und in der Verwaltung weiter aktiv. 

Die log files werden angezeigt aber existieren nicht nach Aufruf. 

Nur am Rande da nicht wirklich Funktions relevant, tritt seit beginn an  ein Fehler auf wenn das backup um hh:00 durchgeführt wird .  

Grüße Andreas 

lox berry 1.4.2.2  ; raspi 3+ ; speicherort Synology NAS

**Comment by Woersty** [comment]
Würde sagen, dein Dateisystem hat's zerlegt.
Hast du den LoxBerry mal neu gestartet?
Entweder geht er dann gar nicht mehr oder ist wieder heile...

**Comment by AndreasSausner** [comment]
Hi,

habe gerade die ursache gefunden. Neustart brachte nichts. es war lag am dateisystem, RootFS war NOK , ich habe ein backup vom vor +-10 tagen wieder restored und… alles OK . es scheint das die SD karte  ..wieder einmal einen fehler aufwies ….. 

THX Andreas
