### ISSUE TITLE
File share on NAS not detected if root folder is not read/write

### ISSUE THREAD

**Issue by begunrom** [Woersty/LoxBerry-Plugin-miniserverbackup#85]
I am backing up to NAS. I have a file structure /data/backup/miniserver. Loxberry has r/w rights starting from miniserver. The plugin does not detect the file share to write onto. It only detects it when I make data read/write (what I prefer not to do).

**Comment by Woersty** [comment]
Will have a look asap but currently I'm busy due to Xmas 😃

**Comment by Woersty** [comment]
Can you mail me a debug log, please?
You can use _git **(at)** loxberry **dot** woerstenfeld **dot** de_

**Comment by begunrom** [comment]
Hi,

If the loxberry user has r/w on the data folder the network storage section
is populated and the file  'check_loxberry_rw_state.tmp' created in the
/data folder.
[image: image.png]

Once you change the rights to the data folder to read only, status changes
to ro and
[image: image.png]
[image: image.png]
I cannot send you any miniserverbackup related logs as I cannot start the
backup to the right location.

Are there any other logs that can help you?

**Comment by Woersty** [comment]
Please send me the log in Debug mode by mail to identify the exact line with the problem.

**Comment by Woersty** [comment]
Maybe related to #96 
Please retry with the current version 2020.7.12.
