### ISSUE TITLE
Fehler-Mail bei Fehlern

### ISSUE THREAD

**Issue by christianTF** [Woersty/LoxBerry-Plugin-miniserverbackup#9]
Cool wäre eine Checkbox, mit der aktiviert werden kann, dass bei Fehlern über die LoxBerry-interne Mailing-Funktion ein Mail verschickt wird.

Fehler wären z.B.
- Miniserver nicht erreichbar
- Anmeldedaten am MS fehlerhaft
- Disk full

lg, Christian

**Comment by gahujipo** [comment]
Man müsste sich aber dann nach jedem Backup ein Mail schicken lassen um festzustellen ob alles korrekt funktioniert: Alarmierung ok und Backup ok. 

Meine Idee wäre gewesen dem Loxone Miniserver ein UDP Paket zu schicken der es seinerseits verwerten kann, wenn er darauf hört. Wäre das eine Idee? Dann könnte man auch abfragen ob das Paket mindestens einmal pro Ausführungsintervall ankommt.

**Comment by Woersty** [comment]
Ist auf der to do Liste.
Aber im Sommer habe ich keine Lust vor dem PC zu hängen... schau ich mir aber mal an.
