### ISSUE TITLE
Compatibility 2.0.2+

### ISSUE THREAD

**Issue by Woersty** [Woersty/LoxBerry-Plugin-miniserverbackup#90]
Fix deprecated LBSystem::read_generalcfg(); in createmsbackup.php @ 213

**Comment by Woersty** [comment]
Partiell gelöst.
Der Fehler wegen der .cfg ist weg aber der Umbau auf .json fehlt noch.

**Comment by christianTF** [comment]
Im Großen und Ganzen kannst du den neuen Code in loxberry_system.php (wo das json gelesen wird) auch wieder 1:1 übernehmen.
Das PreferHttps / PortHttps gibt's in der general.cfg nicht, das gibt's nur im json.

**Comment by Woersty** [comment]
Ok.. kommt auf die ToDo Liste für diese Woche
