### ISSUE TITLE
Zusätzliches Unterverzeichnis im Archiv

### ISSUE THREAD

**Issue by mschlenstedt** [Woersty/LoxBerry-Plugin-miniserverbackup#91]
Im Backup-Archiv wird ein zusätzliches Verzeichnis mit der Miniservernummer und dem Namen angelegt. Mit diesem Verzeichnis erkennt LoxoneConfig das Backup nicht.

![image](https://user-images.githubusercontent.com/16830799/77860088-83d2e800-720d-11ea-8019-76301b28b214.png)

**Comment by mschlenstedt** [comment]
Betrifft nur den Sicherungstyp 7-Zip. Bei ZIP und "unkomprimiert" ist es OK.

**Comment by Woersty** [comment]
Ab Version 2020.04.19 wird in 7z Archiven das Wurzelverzeichnis "001_Miniservername" nicht mehr mitgesichert - nur der Inhalt.
From Version 2020.04.19 is in 7z archives the root folder "001_Miniservername" not stored anymore - just the content.
